In [20]:
from alist import save_as_npz
import os
import numpy as np
import tensorflow as tf

#Convert alist to matrices and save code as npz
codename = "LDPC/n64_k46_m18_dv4_dc14-15"
save_as_npz(code_name=codename, main_save_path="./")

code_path = os.path.join('./', f'{codename}.npz')

code_file = np.load(code_path)
# print(code_file.files)


G_sys = tf.convert_to_tensor(code_file['G'], dtype=tf.float32)
H_sys = tf.convert_to_tensor(code_file['H_systematic'], dtype=tf.float32)
H_nsys = tf.convert_to_tensor(code_file['H_non_systematic'], dtype=tf.float32)

print("G SYS")
tf.print(G_sys,summarize=-1)
print("H SYS")
tf.print(H_sys,summarize=-1)
print("H NON SYS")
tf.print(H_nsys,summarize=-1)
print("G SYS x H SYS")
tf.print(tf.matmul(G_sys,tf.transpose(H_sys))%2,summarize=-1)
print("G SYS x H NON SYS")
tf.print(tf.matmul(G_sys,tf.transpose(H_nsys))%2,summarize=-1)

G SYS
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 1 0 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0